# Generated by Django 5.0.4 on 2024-07-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
    ]
