# Generated by Django 5.0.4 on 2024-07-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_student_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('languages_used', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
    ]
