# Generated by Django 5.0.4 on 2024-07-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_deafult_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
